//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public double total_price { get; set; }
        public System.DateTime order_date { get; set; }
        public int seller_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual seller seller { get; set; }
    }
}
