//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        public int doctor_id { get; set; }
        public string doctor_name { get; set; }
        public string doctor_addressline_1 { get; set; }
        public string doctor_addressline_2 { get; set; }
        public string doctor_city { get; set; }
        public int doctor_phone_no { get; set; }
        public string doctor_department { get; set; }
    }
}
