//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmacyApp_DBEntities5 : DbContext
    {
        public PharmacyApp_DBEntities5()
            : base("name=PharmacyApp_DBEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<doctor> doctors { get; set; }
        public virtual DbSet<medicine> medicines { get; set; }
        public virtual DbSet<order_details> order_details { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<payment_info> payment_info { get; set; }
        public virtual DbSet<seller> sellers { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<seller_medicine> seller_medicine { get; set; }
    }
}
