//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class seller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seller()
        {
            this.bills = new HashSet<bill>();
            this.seller_medicine = new HashSet<seller_medicine>();
        }
    
        public int seller_id { get; set; }
        public string seller_name { get; set; }
        public string seller_email { get; set; }
        public decimal seller_phone_no { get; set; }
        public string seller_addressline_1 { get; set; }
        public string seller_addressline_2 { get; set; }
        public string seller_city { get; set; }
        public string seller_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seller_medicine> seller_medicine { get; set; }
    }
}
